// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxgonlrxebsipnxyfvmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94Z29ubHJ4ZWJzaXBueHlmdm1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMTIwNDQsImV4cCI6MjA3MDc4ODA0NH0.S1zy8UDqoj5uxzGm7Vrqlg7mmPHm2gv3TYZ13EwS9AA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});